/** Static S&P 500 constituents (Symbol + GICS). Snapshot for screener filters; refresh periodically. */
export type Sp500Meta = { sector: string; industry: string };
export const SP500_BY_TICKER: Record<string, Sp500Meta> = {
  'MMM': { sector: 'Industrials', industry: 'Industrial Conglomerates' },
  'AOS': { sector: 'Industrials', industry: 'Building Products' },
  'ABT': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'ABBV': { sector: 'Health Care', industry: 'Biotechnology' },
  'ACN': { sector: 'Information Technology', industry: 'IT Consulting & Other Services' },
  'ADBE': { sector: 'Information Technology', industry: 'Application Software' },
  'AMD': { sector: 'Information Technology', industry: 'Semiconductors' },
  'AES': { sector: 'Utilities', industry: 'Independent Power Producers & Energy Traders' },
  'AFL': { sector: 'Financials', industry: 'Life & Health Insurance' },
  'A': { sector: 'Health Care', industry: 'Life Sciences Tools & Services' },
  'APD': { sector: 'Materials', industry: 'Industrial Gases' },
  'ABNB': { sector: 'Consumer Discretionary', industry: 'Hotels, Resorts & Cruise Lines' },
  'AKAM': { sector: 'Information Technology', industry: 'Internet Services & Infrastructure' },
  'ALB': { sector: 'Materials', industry: 'Specialty Chemicals' },
  'ARE': { sector: 'Real Estate', industry: 'Office REITs' },
  'ALGN': { sector: 'Health Care', industry: 'Health Care Supplies' },
  'ALLE': { sector: 'Industrials', industry: 'Building Products' },
  'LNT': { sector: 'Utilities', industry: 'Electric Utilities' },
  'ALL': { sector: 'Financials', industry: 'Property & Casualty Insurance' },
  'GOOGL': { sector: 'Communication Services', industry: 'Interactive Media & Services' },
  'GOOG': { sector: 'Communication Services', industry: 'Interactive Media & Services' },
  'MO': { sector: 'Consumer Staples', industry: 'Tobacco' },
  'AMZN': { sector: 'Consumer Discretionary', industry: 'Broadline Retail' },
  'AMCR': { sector: 'Materials', industry: 'Paper & Plastic Packaging Products & Materials' },
  'AEE': { sector: 'Utilities', industry: 'Multi-Utilities' },
  'AEP': { sector: 'Utilities', industry: 'Electric Utilities' },
  'AXP': { sector: 'Financials', industry: 'Consumer Finance' },
  'AIG': { sector: 'Financials', industry: 'Multi-line Insurance' },
  'AMT': { sector: 'Real Estate', industry: 'Telecom Tower REITs' },
  'AWK': { sector: 'Utilities', industry: 'Water Utilities' },
  'AMP': { sector: 'Financials', industry: 'Asset Management & Custody Banks' },
  'AME': { sector: 'Industrials', industry: 'Electrical Components & Equipment' },
  'AMGN': { sector: 'Health Care', industry: 'Biotechnology' },
  'APH': { sector: 'Information Technology', industry: 'Electronic Components' },
  'ADI': { sector: 'Information Technology', industry: 'Semiconductors' },
  'AON': { sector: 'Financials', industry: 'Insurance Brokers' },
  'APA': { sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  'APO': { sector: 'Financials', industry: 'Asset Management & Custody Banks' },
  'AAPL': { sector: 'Information Technology', industry: 'Technology Hardware, Storage & Peripherals' },
  'AMAT': { sector: 'Information Technology', industry: 'Semiconductor Materials & Equipment' },
  'APP': { sector: 'Communication Services', industry: 'Advertising' },
  'APTV': { sector: 'Consumer Discretionary', industry: 'Automotive Parts & Equipment' },
  'ACGL': { sector: 'Financials', industry: 'Property & Casualty Insurance' },
  'ADM': { sector: 'Consumer Staples', industry: 'Agricultural Products & Services' },
  'ARES': { sector: 'Financials', industry: 'Asset Management & Custody Banks' },
  'ANET': { sector: 'Information Technology', industry: 'Communications Equipment' },
  'AJG': { sector: 'Financials', industry: 'Insurance Brokers' },
  'AIZ': { sector: 'Financials', industry: 'Multi-line Insurance' },
  'T': { sector: 'Communication Services', industry: 'Integrated Telecommunication Services' },
  'ATO': { sector: 'Utilities', industry: 'Gas Utilities' },
  'ADSK': { sector: 'Information Technology', industry: 'Application Software' },
  'ADP': { sector: 'Industrials', industry: 'Human Resource & Employment Services' },
  'AZO': { sector: 'Consumer Discretionary', industry: 'Automotive Retail' },
  'AVY': { sector: 'Materials', industry: 'Paper & Plastic Packaging Products & Materials' },
  'AXON': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'BKR': { sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  'BALL': { sector: 'Materials', industry: 'Metal, Glass & Plastic Containers' },
  'BAC': { sector: 'Financials', industry: 'Diversified Banks' },
  'BAX': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'BDX': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'BRK-B': { sector: 'Financials', industry: 'Multi-Sector Holdings' },
  'BRK.B': { sector: 'Financials', industry: 'Multi-Sector Holdings' },
  'BBY': { sector: 'Consumer Discretionary', industry: 'Computer & Electronics Retail' },
  'TECH': { sector: 'Health Care', industry: 'Life Sciences Tools & Services' },
  'BIIB': { sector: 'Health Care', industry: 'Biotechnology' },
  'BLK': { sector: 'Financials', industry: 'Asset Management & Custody Banks' },
  'BX': { sector: 'Financials', industry: 'Asset Management & Custody Banks' },
  'XYZ': { sector: 'Financials', industry: 'Transaction & Payment Processing Services' },
  'BE': { sector: 'Industrials', industry: 'Electrical Components & Equipment' },
  'BNY': { sector: 'Financials', industry: 'Asset Management & Custody Banks' },
  'BA': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'BKNG': { sector: 'Consumer Discretionary', industry: 'Hotels, Resorts & Cruise Lines' },
  'BSX': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'BMY': { sector: 'Health Care', industry: 'Pharmaceuticals' },
  'AVGO': { sector: 'Information Technology', industry: 'Semiconductors' },
  'BR': { sector: 'Industrials', industry: 'Data Processing & Outsourced Services' },
  'BRO': { sector: 'Financials', industry: 'Insurance Brokers' },
  'BF-B': { sector: 'Consumer Staples', industry: 'Distillers & Vintners' },
  'BF.B': { sector: 'Consumer Staples', industry: 'Distillers & Vintners' },
  'BG': { sector: 'Consumer Staples', industry: 'Agricultural Products & Services' },
  'BXP': { sector: 'Real Estate', industry: 'Office REITs' },
  'CHRW': { sector: 'Industrials', industry: 'Air Freight & Logistics' },
  'CDNS': { sector: 'Information Technology', industry: 'Application Software' },
  'CPT': { sector: 'Real Estate', industry: 'Multi-Family Residential REITs' },
  'COF': { sector: 'Financials', industry: 'Consumer Finance' },
  'CAH': { sector: 'Health Care', industry: 'Health Care Distributors' },
  'CCL': { sector: 'Consumer Discretionary', industry: 'Hotels, Resorts & Cruise Lines' },
  'CARR': { sector: 'Industrials', industry: 'Building Products' },
  'CVNA': { sector: 'Consumer Discretionary', industry: 'Automotive Retail' },
  'CASY': { sector: 'Consumer Staples', industry: 'Food Retail' },
  'CAT': { sector: 'Industrials', industry: 'Construction Machinery & Heavy Transportation Equipment' },
  'CBOE': { sector: 'Financials', industry: 'Financial Exchanges & Data' },
  'CBRE': { sector: 'Real Estate', industry: 'Real Estate Services' },
  'CDW': { sector: 'Information Technology', industry: 'Technology Distributors' },
  'COR': { sector: 'Health Care', industry: 'Health Care Distributors' },
  'CNC': { sector: 'Health Care', industry: 'Managed Health Care' },
  'CNP': { sector: 'Utilities', industry: 'Multi-Utilities' },
  'CF': { sector: 'Materials', industry: 'Fertilizers & Agricultural Chemicals' },
  'CRL': { sector: 'Health Care', industry: 'Life Sciences Tools & Services' },
  'SCHW': { sector: 'Financials', industry: 'Investment Banking & Brokerage' },
  'CHTR': { sector: 'Communication Services', industry: 'Cable & Satellite' },
  'CVX': { sector: 'Energy', industry: 'Integrated Oil & Gas' },
  'CMG': { sector: 'Consumer Discretionary', industry: 'Restaurants' },
  'CB': { sector: 'Financials', industry: 'Property & Casualty Insurance' },
  'CHD': { sector: 'Consumer Staples', industry: 'Household Products' },
  'CIEN': { sector: 'Information Technology', industry: 'Communications Equipment' },
  'CI': { sector: 'Health Care', industry: 'Health Care Services' },
  'CINF': { sector: 'Financials', industry: 'Property & Casualty Insurance' },
  'CTAS': { sector: 'Industrials', industry: 'Diversified Support Services' },
  'CSCO': { sector: 'Information Technology', industry: 'Communications Equipment' },
  'C': { sector: 'Financials', industry: 'Diversified Banks' },
  'CFG': { sector: 'Financials', industry: 'Regional Banks' },
  'CLX': { sector: 'Consumer Staples', industry: 'Household Products' },
  'CME': { sector: 'Financials', industry: 'Financial Exchanges & Data' },
  'CMS': { sector: 'Utilities', industry: 'Multi-Utilities' },
  'KO': { sector: 'Consumer Staples', industry: 'Soft Drinks & Non-alcoholic Beverages' },
  'CTSH': { sector: 'Information Technology', industry: 'IT Consulting & Other Services' },
  'COHR': { sector: 'Information Technology', industry: 'Electronic Components' },
  'COIN': { sector: 'Financials', industry: 'Financial Exchanges & Data' },
  'CL': { sector: 'Consumer Staples', industry: 'Household Products' },
  'CMCSA': { sector: 'Communication Services', industry: 'Cable & Satellite' },
  'FIX': { sector: 'Industrials', industry: 'Construction & Engineering' },
  'COP': { sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  'ED': { sector: 'Utilities', industry: 'Multi-Utilities' },
  'STZ': { sector: 'Consumer Staples', industry: 'Distillers & Vintners' },
  'CEG': { sector: 'Utilities', industry: 'Electric Utilities' },
  'COO': { sector: 'Health Care', industry: 'Health Care Supplies' },
  'CPRT': { sector: 'Industrials', industry: 'Diversified Support Services' },
  'GLW': { sector: 'Information Technology', industry: 'Electronic Components' },
  'CPAY': { sector: 'Financials', industry: 'Transaction & Payment Processing Services' },
  'CTVA': { sector: 'Materials', industry: 'Fertilizers & Agricultural Chemicals' },
  'CSGP': { sector: 'Real Estate', industry: 'Real Estate Services' },
  'COST': { sector: 'Consumer Staples', industry: 'Consumer Staples Merchandise Retail' },
  'CRH': { sector: 'Materials', industry: 'Construction Materials' },
  'CRWD': { sector: 'Information Technology', industry: 'Systems Software' },
  'CCI': { sector: 'Real Estate', industry: 'Telecom Tower REITs' },
  'CSX': { sector: 'Industrials', industry: 'Rail Transportation' },
  'CMI': { sector: 'Industrials', industry: 'Construction Machinery & Heavy Transportation Equipment' },
  'CVS': { sector: 'Health Care', industry: 'Health Care Services' },
  'DHR': { sector: 'Health Care', industry: 'Life Sciences Tools & Services' },
  'DRI': { sector: 'Consumer Discretionary', industry: 'Restaurants' },
  'DDOG': { sector: 'Information Technology', industry: 'Application Software' },
  'DVA': { sector: 'Health Care', industry: 'Health Care Services' },
  'DECK': { sector: 'Consumer Discretionary', industry: 'Footwear' },
  'DE': { sector: 'Industrials', industry: 'Agricultural & Farm Machinery' },
  'DELL': { sector: 'Information Technology', industry: 'Technology Hardware, Storage & Peripherals' },
  'DAL': { sector: 'Industrials', industry: 'Passenger Airlines' },
  'DVN': { sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  'DXCM': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'FANG': { sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  'DLR': { sector: 'Real Estate', industry: 'Data Center REITs' },
  'DG': { sector: 'Consumer Staples', industry: 'Consumer Staples Merchandise Retail' },
  'DLTR': { sector: 'Consumer Staples', industry: 'Consumer Staples Merchandise Retail' },
  'D': { sector: 'Utilities', industry: 'Multi-Utilities' },
  'DPZ': { sector: 'Consumer Discretionary', industry: 'Restaurants' },
  'DASH': { sector: 'Consumer Discretionary', industry: 'Specialized Consumer Services' },
  'DOV': { sector: 'Industrials', industry: 'Industrial Machinery & Supplies & Components' },
  'DOW': { sector: 'Materials', industry: 'Commodity Chemicals' },
  'DHI': { sector: 'Consumer Discretionary', industry: 'Homebuilding' },
  'DTE': { sector: 'Utilities', industry: 'Multi-Utilities' },
  'DUK': { sector: 'Utilities', industry: 'Electric Utilities' },
  'DD': { sector: 'Industrials', industry: 'Industrial Conglomerates' },
  'ETN': { sector: 'Industrials', industry: 'Electrical Components & Equipment' },
  'EBAY': { sector: 'Consumer Discretionary', industry: 'Broadline Retail' },
  'ECHO': { sector: 'Communication Services', industry: 'Wireless Telecommunication Services' },
  'ECL': { sector: 'Materials', industry: 'Specialty Chemicals' },
  'EIX': { sector: 'Utilities', industry: 'Electric Utilities' },
  'EW': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'ELV': { sector: 'Health Care', industry: 'Managed Health Care' },
  'EME': { sector: 'Industrials', industry: 'Construction & Engineering' },
  'EMR': { sector: 'Industrials', industry: 'Electrical Components & Equipment' },
  'ETR': { sector: 'Utilities', industry: 'Electric Utilities' },
  'EOG': { sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  'EQT': { sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  'EFX': { sector: 'Industrials', industry: 'Research & Consulting Services' },
  'EQIX': { sector: 'Real Estate', industry: 'Data Center REITs' },
  'ERIE': { sector: 'Financials', industry: 'Insurance Brokers' },
  'ESS': { sector: 'Real Estate', industry: 'Multi-Family Residential REITs' },
  'EL': { sector: 'Consumer Staples', industry: 'Personal Care Products' },
  'EG': { sector: 'Financials', industry: 'Reinsurance' },
  'EVRG': { sector: 'Utilities', industry: 'Electric Utilities' },
  'P': { sector: 'Information Technology', industry: 'Technology Hardware, Storage & Peripherals' },
  'ES': { sector: 'Utilities', industry: 'Electric Utilities' },
  'EXC': { sector: 'Utilities', industry: 'Electric Utilities' },
  'EXE': { sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  'EXPE': { sector: 'Consumer Discretionary', industry: 'Hotels, Resorts & Cruise Lines' },
  'EXPD': { sector: 'Industrials', industry: 'Air Freight & Logistics' },
  'EXR': { sector: 'Real Estate', industry: 'Self-Storage REITs' },
  'XOM': { sector: 'Energy', industry: 'Integrated Oil & Gas' },
  'FFIV': { sector: 'Information Technology', industry: 'Communications Equipment' },
  'FDS': { sector: 'Financials', industry: 'Financial Exchanges & Data' },
  'FICO': { sector: 'Information Technology', industry: 'Application Software' },
  'FAST': { sector: 'Industrials', industry: 'Trading Companies & Distributors' },
  'FRT': { sector: 'Real Estate', industry: 'Retail REITs' },
  'FDX': { sector: 'Industrials', industry: 'Air Freight & Logistics' },
  'FDXF': { sector: 'Industrials', industry: 'Cargo Ground Transportation' },
  'FERG': { sector: 'Industrials', industry: 'Trading Companies & Distributors' },
  'FIS': { sector: 'Financials', industry: 'Transaction & Payment Processing Services' },
  'FITB': { sector: 'Financials', industry: 'Regional Banks' },
  'FSLR': { sector: 'Information Technology', industry: 'Semiconductors' },
  'FE': { sector: 'Utilities', industry: 'Electric Utilities' },
  'FISV': { sector: 'Financials', industry: 'Transaction & Payment Processing Services' },
  'FLEX': { sector: 'Information Technology', industry: 'Electronic Manufacturing Services' },
  'F': { sector: 'Consumer Discretionary', industry: 'Automobile Manufacturers' },
  'FTNT': { sector: 'Information Technology', industry: 'Systems Software' },
  'FTV': { sector: 'Industrials', industry: 'Industrial Machinery & Supplies & Components' },
  'FOXA': { sector: 'Communication Services', industry: 'Broadcasting' },
  'FOX': { sector: 'Communication Services', industry: 'Broadcasting' },
  'BEN': { sector: 'Financials', industry: 'Asset Management & Custody Banks' },
  'FCX': { sector: 'Materials', industry: 'Copper' },
  'GRMN': { sector: 'Consumer Discretionary', industry: 'Consumer Electronics' },
  'IT': { sector: 'Information Technology', industry: 'IT Consulting & Other Services' },
  'GE': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'GEHC': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'GEV': { sector: 'Industrials', industry: 'Heavy Electrical Equipment' },
  'GEN': { sector: 'Information Technology', industry: 'Systems Software' },
  'GNRC': { sector: 'Industrials', industry: 'Heavy Electrical Equipment' },
  'GD': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'GIS': { sector: 'Consumer Staples', industry: 'Packaged Foods & Meats' },
  'GM': { sector: 'Consumer Discretionary', industry: 'Automobile Manufacturers' },
  'GPC': { sector: 'Consumer Discretionary', industry: 'Distributors' },
  'GILD': { sector: 'Health Care', industry: 'Biotechnology' },
  'GPN': { sector: 'Financials', industry: 'Transaction & Payment Processing Services' },
  'GL': { sector: 'Financials', industry: 'Life & Health Insurance' },
  'GDDY': { sector: 'Information Technology', industry: 'Internet Services & Infrastructure' },
  'GS': { sector: 'Financials', industry: 'Investment Banking & Brokerage' },
  'HAL': { sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  'HIG': { sector: 'Financials', industry: 'Property & Casualty Insurance' },
  'HAS': { sector: 'Consumer Discretionary', industry: 'Leisure Products' },
  'HCA': { sector: 'Health Care', industry: 'Health Care Facilities' },
  'DOC': { sector: 'Real Estate', industry: 'Health Care REITs' },
  'HSIC': { sector: 'Health Care', industry: 'Health Care Distributors' },
  'HSY': { sector: 'Consumer Staples', industry: 'Packaged Foods & Meats' },
  'HPE': { sector: 'Information Technology', industry: 'Technology Hardware, Storage & Peripherals' },
  'HLT': { sector: 'Consumer Discretionary', industry: 'Hotels, Resorts & Cruise Lines' },
  'HD': { sector: 'Consumer Discretionary', industry: 'Home Improvement Retail' },
  'HONA': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'HON': { sector: 'Industrials', industry: 'Industrial Conglomerates' },
  'HRL': { sector: 'Consumer Staples', industry: 'Packaged Foods & Meats' },
  'HST': { sector: 'Real Estate', industry: 'Hotel & Resort REITs' },
  'HWM': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'HPQ': { sector: 'Information Technology', industry: 'Technology Hardware, Storage & Peripherals' },
  'HUBB': { sector: 'Industrials', industry: 'Industrial Machinery & Supplies & Components' },
  'HUM': { sector: 'Health Care', industry: 'Managed Health Care' },
  'HBAN': { sector: 'Financials', industry: 'Regional Banks' },
  'HII': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'IBM': { sector: 'Information Technology', industry: 'IT Consulting & Other Services' },
  'IEX': { sector: 'Industrials', industry: 'Industrial Machinery & Supplies & Components' },
  'IDXX': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'ITW': { sector: 'Industrials', industry: 'Industrial Machinery & Supplies & Components' },
  'ILMN': { sector: 'Health Care', industry: 'Life Sciences Tools & Services' },
  'INCY': { sector: 'Health Care', industry: 'Biotechnology' },
  'IR': { sector: 'Industrials', industry: 'Industrial Machinery & Supplies & Components' },
  'PODD': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'INTC': { sector: 'Information Technology', industry: 'Semiconductors' },
  'IBKR': { sector: 'Financials', industry: 'Investment Banking & Brokerage' },
  'ICE': { sector: 'Financials', industry: 'Financial Exchanges & Data' },
  'IFF': { sector: 'Materials', industry: 'Specialty Chemicals' },
  'IP': { sector: 'Materials', industry: 'Paper & Plastic Packaging Products & Materials' },
  'INTU': { sector: 'Information Technology', industry: 'Application Software' },
  'ISRG': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'IVZ': { sector: 'Financials', industry: 'Asset Management & Custody Banks' },
  'INVH': { sector: 'Real Estate', industry: 'Single-Family Residential REITs' },
  'IQV': { sector: 'Health Care', industry: 'Life Sciences Tools & Services' },
  'IRM': { sector: 'Real Estate', industry: 'Other Specialized REITs' },
  'JBHT': { sector: 'Industrials', industry: 'Cargo Ground Transportation' },
  'JBL': { sector: 'Information Technology', industry: 'Electronic Manufacturing Services' },
  'JKHY': { sector: 'Financials', industry: 'Transaction & Payment Processing Services' },
  'J': { sector: 'Industrials', industry: 'Construction & Engineering' },
  'JNJ': { sector: 'Health Care', industry: 'Pharmaceuticals' },
  'JCI': { sector: 'Industrials', industry: 'Building Products' },
  'JPM': { sector: 'Financials', industry: 'Diversified Banks' },
  'KVUE': { sector: 'Consumer Staples', industry: 'Personal Care Products' },
  'KDP': { sector: 'Consumer Staples', industry: 'Soft Drinks & Non-alcoholic Beverages' },
  'KEY': { sector: 'Financials', industry: 'Regional Banks' },
  'KEYS': { sector: 'Information Technology', industry: 'Electronic Equipment & Instruments' },
  'KMB': { sector: 'Consumer Staples', industry: 'Household Products' },
  'KIM': { sector: 'Real Estate', industry: 'Retail REITs' },
  'KMI': { sector: 'Energy', industry: 'Oil & Gas Storage & Transportation' },
  'KKR': { sector: 'Financials', industry: 'Asset Management & Custody Banks' },
  'KLAC': { sector: 'Information Technology', industry: 'Semiconductor Materials & Equipment' },
  'KHC': { sector: 'Consumer Staples', industry: 'Packaged Foods & Meats' },
  'KR': { sector: 'Consumer Staples', industry: 'Food Retail' },
  'LHX': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'LH': { sector: 'Health Care', industry: 'Health Care Services' },
  'LRCX': { sector: 'Information Technology', industry: 'Semiconductor Materials & Equipment' },
  'LVS': { sector: 'Consumer Discretionary', industry: 'Casinos & Gaming' },
  'LDOS': { sector: 'Industrials', industry: 'Diversified Support Services' },
  'LEN': { sector: 'Consumer Discretionary', industry: 'Homebuilding' },
  'LII': { sector: 'Industrials', industry: 'Building Products' },
  'LLY': { sector: 'Health Care', industry: 'Pharmaceuticals' },
  'LIN': { sector: 'Materials', industry: 'Industrial Gases' },
  'LYV': { sector: 'Communication Services', industry: 'Movies & Entertainment' },
  'LMT': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'L': { sector: 'Financials', industry: 'Multi-line Insurance' },
  'LOW': { sector: 'Consumer Discretionary', industry: 'Home Improvement Retail' },
  'LULU': { sector: 'Consumer Discretionary', industry: 'Apparel, Accessories & Luxury Goods' },
  'LITE': { sector: 'Information Technology', industry: 'Communications Equipment' },
  'LYB': { sector: 'Materials', industry: 'Specialty Chemicals' },
  'MTB': { sector: 'Financials', industry: 'Regional Banks' },
  'MPC': { sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  'MAR': { sector: 'Consumer Discretionary', industry: 'Hotels, Resorts & Cruise Lines' },
  'MRSH': { sector: 'Financials', industry: 'Insurance Brokers' },
  'MLM': { sector: 'Materials', industry: 'Construction Materials' },
  'MRVL': { sector: 'Information Technology', industry: 'Semiconductors' },
  'MAS': { sector: 'Industrials', industry: 'Building Products' },
  'MA': { sector: 'Financials', industry: 'Transaction & Payment Processing Services' },
  'MKC': { sector: 'Consumer Staples', industry: 'Packaged Foods & Meats' },
  'MCD': { sector: 'Consumer Discretionary', industry: 'Restaurants' },
  'MCK': { sector: 'Health Care', industry: 'Health Care Distributors' },
  'MDT': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'MRK': { sector: 'Health Care', industry: 'Pharmaceuticals' },
  'META': { sector: 'Communication Services', industry: 'Interactive Media & Services' },
  'MET': { sector: 'Financials', industry: 'Life & Health Insurance' },
  'MTD': { sector: 'Health Care', industry: 'Life Sciences Tools & Services' },
  'MGM': { sector: 'Consumer Discretionary', industry: 'Casinos & Gaming' },
  'MCHP': { sector: 'Information Technology', industry: 'Semiconductors' },
  'MU': { sector: 'Information Technology', industry: 'Semiconductors' },
  'MSFT': { sector: 'Information Technology', industry: 'Systems Software' },
  'MAA': { sector: 'Real Estate', industry: 'Multi-Family Residential REITs' },
  'MRNA': { sector: 'Health Care', industry: 'Biotechnology' },
  'MDLZ': { sector: 'Consumer Staples', industry: 'Packaged Foods & Meats' },
  'MPWR': { sector: 'Information Technology', industry: 'Semiconductors' },
  'MNST': { sector: 'Consumer Staples', industry: 'Soft Drinks & Non-alcoholic Beverages' },
  'MCO': { sector: 'Financials', industry: 'Financial Exchanges & Data' },
  'MS': { sector: 'Financials', industry: 'Investment Banking & Brokerage' },
  'MOS': { sector: 'Materials', industry: 'Fertilizers & Agricultural Chemicals' },
  'MSI': { sector: 'Information Technology', industry: 'Communications Equipment' },
  'MSCI': { sector: 'Financials', industry: 'Financial Exchanges & Data' },
  'NDAQ': { sector: 'Financials', industry: 'Financial Exchanges & Data' },
  'NTAP': { sector: 'Information Technology', industry: 'Technology Hardware, Storage & Peripherals' },
  'NFLX': { sector: 'Communication Services', industry: 'Movies & Entertainment' },
  'NEM': { sector: 'Materials', industry: 'Gold' },
  'NWSA': { sector: 'Communication Services', industry: 'Publishing' },
  'NWS': { sector: 'Communication Services', industry: 'Publishing' },
  'NEE': { sector: 'Utilities', industry: 'Multi-Utilities' },
  'NKE': { sector: 'Consumer Discretionary', industry: 'Apparel, Accessories & Luxury Goods' },
  'NI': { sector: 'Utilities', industry: 'Multi-Utilities' },
  'NDSN': { sector: 'Industrials', industry: 'Industrial Machinery & Supplies & Components' },
  'NSC': { sector: 'Industrials', industry: 'Rail Transportation' },
  'NTRS': { sector: 'Financials', industry: 'Asset Management & Custody Banks' },
  'NOC': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'NCLH': { sector: 'Consumer Discretionary', industry: 'Hotels, Resorts & Cruise Lines' },
  'NRG': { sector: 'Utilities', industry: 'Independent Power Producers & Energy Traders' },
  'NUE': { sector: 'Materials', industry: 'Steel' },
  'NVDA': { sector: 'Information Technology', industry: 'Semiconductors' },
  'NVR': { sector: 'Consumer Discretionary', industry: 'Homebuilding' },
  'NXPI': { sector: 'Information Technology', industry: 'Semiconductors' },
  'ORLY': { sector: 'Consumer Discretionary', industry: 'Automotive Retail' },
  'OXY': { sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  'ODFL': { sector: 'Industrials', industry: 'Cargo Ground Transportation' },
  'OMC': { sector: 'Communication Services', industry: 'Advertising' },
  'ON': { sector: 'Information Technology', industry: 'Semiconductors' },
  'OKE': { sector: 'Energy', industry: 'Oil & Gas Storage & Transportation' },
  'ORCL': { sector: 'Information Technology', industry: 'Application Software' },
  'OTIS': { sector: 'Industrials', industry: 'Industrial Machinery & Supplies & Components' },
  'PCAR': { sector: 'Industrials', industry: 'Construction Machinery & Heavy Transportation Equipment' },
  'PKG': { sector: 'Materials', industry: 'Paper & Plastic Packaging Products & Materials' },
  'PLTR': { sector: 'Information Technology', industry: 'Application Software' },
  'PANW': { sector: 'Information Technology', industry: 'Systems Software' },
  'PSKY': { sector: 'Communication Services', industry: 'Movies & Entertainment' },
  'PH': { sector: 'Industrials', industry: 'Industrial Machinery & Supplies & Components' },
  'PAYX': { sector: 'Industrials', industry: 'Human Resource & Employment Services' },
  'PYPL': { sector: 'Financials', industry: 'Transaction & Payment Processing Services' },
  'PNR': { sector: 'Industrials', industry: 'Industrial Machinery & Supplies & Components' },
  'PEP': { sector: 'Consumer Staples', industry: 'Soft Drinks & Non-alcoholic Beverages' },
  'PFE': { sector: 'Health Care', industry: 'Pharmaceuticals' },
  'PCG': { sector: 'Utilities', industry: 'Multi-Utilities' },
  'PM': { sector: 'Consumer Staples', industry: 'Tobacco' },
  'PSX': { sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  'PNW': { sector: 'Utilities', industry: 'Multi-Utilities' },
  'PNC': { sector: 'Financials', industry: 'Diversified Banks' },
  'PPG': { sector: 'Materials', industry: 'Specialty Chemicals' },
  'PPL': { sector: 'Utilities', industry: 'Electric Utilities' },
  'PFG': { sector: 'Financials', industry: 'Life & Health Insurance' },
  'PG': { sector: 'Consumer Staples', industry: 'Personal Care Products' },
  'PGR': { sector: 'Financials', industry: 'Property & Casualty Insurance' },
  'PLD': { sector: 'Real Estate', industry: 'Industrial REITs' },
  'PRU': { sector: 'Financials', industry: 'Life & Health Insurance' },
  'PEG': { sector: 'Utilities', industry: 'Electric Utilities' },
  'PTC': { sector: 'Information Technology', industry: 'Application Software' },
  'PSA': { sector: 'Real Estate', industry: 'Self-Storage REITs' },
  'PHM': { sector: 'Consumer Discretionary', industry: 'Homebuilding' },
  'PWR': { sector: 'Industrials', industry: 'Construction & Engineering' },
  'QCOM': { sector: 'Information Technology', industry: 'Semiconductors' },
  'DGX': { sector: 'Health Care', industry: 'Health Care Services' },
  'Q': { sector: 'Information Technology', industry: 'Semiconductor Materials & Equipment' },
  'RL': { sector: 'Consumer Discretionary', industry: 'Apparel, Accessories & Luxury Goods' },
  'RJF': { sector: 'Financials', industry: 'Investment Banking & Brokerage' },
  'RDDT': { sector: 'Communication Services', industry: 'Interactive Media & Services' },
  'RTX': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'O': { sector: 'Real Estate', industry: 'Retail REITs' },
  'REG': { sector: 'Real Estate', industry: 'Retail REITs' },
  'REGN': { sector: 'Health Care', industry: 'Biotechnology' },
  'RF': { sector: 'Financials', industry: 'Regional Banks' },
  'RSG': { sector: 'Industrials', industry: 'Environmental & Facilities Services' },
  'RMD': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'RVTY': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'HOOD': { sector: 'Financials', industry: 'Investment Banking & Brokerage' },
  'ROK': { sector: 'Industrials', industry: 'Electrical Components & Equipment' },
  'ROL': { sector: 'Industrials', industry: 'Environmental & Facilities Services' },
  'ROP': { sector: 'Information Technology', industry: 'Electronic Equipment & Instruments' },
  'ROST': { sector: 'Consumer Discretionary', industry: 'Apparel Retail' },
  'RCL': { sector: 'Consumer Discretionary', industry: 'Hotels, Resorts & Cruise Lines' },
  'SPGI': { sector: 'Financials', industry: 'Financial Exchanges & Data' },
  'CRM': { sector: 'Information Technology', industry: 'Application Software' },
  'SNDK': { sector: 'Information Technology', industry: 'Technology Hardware, Storage & Peripherals' },
  'SBAC': { sector: 'Real Estate', industry: 'Telecom Tower REITs' },
  'SLB': { sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  'STX': { sector: 'Information Technology', industry: 'Technology Hardware, Storage & Peripherals' },
  'SRE': { sector: 'Utilities', industry: 'Multi-Utilities' },
  'NOW': { sector: 'Information Technology', industry: 'Systems Software' },
  'SHW': { sector: 'Materials', industry: 'Specialty Chemicals' },
  'SPG': { sector: 'Real Estate', industry: 'Retail REITs' },
  'SWKS': { sector: 'Information Technology', industry: 'Semiconductors' },
  'SJM': { sector: 'Consumer Staples', industry: 'Packaged Foods & Meats' },
  'SW': { sector: 'Materials', industry: 'Paper & Plastic Packaging Products & Materials' },
  'SNA': { sector: 'Industrials', industry: 'Industrial Machinery & Supplies & Components' },
  'SOLV': { sector: 'Health Care', industry: 'Health Care Technology' },
  'SO': { sector: 'Utilities', industry: 'Electric Utilities' },
  'LUV': { sector: 'Industrials', industry: 'Passenger Airlines' },
  'SWK': { sector: 'Industrials', industry: 'Industrial Machinery & Supplies & Components' },
  'SBUX': { sector: 'Consumer Discretionary', industry: 'Restaurants' },
  'STT': { sector: 'Financials', industry: 'Asset Management & Custody Banks' },
  'STLD': { sector: 'Materials', industry: 'Steel' },
  'STE': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'SYK': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'SMCI': { sector: 'Information Technology', industry: 'Technology Hardware, Storage & Peripherals' },
  'SYF': { sector: 'Financials', industry: 'Consumer Finance' },
  'SNPS': { sector: 'Information Technology', industry: 'Application Software' },
  'SYY': { sector: 'Consumer Staples', industry: 'Food Distributors' },
  'TMUS': { sector: 'Communication Services', industry: 'Wireless Telecommunication Services' },
  'TROW': { sector: 'Financials', industry: 'Asset Management & Custody Banks' },
  'TTWO': { sector: 'Communication Services', industry: 'Interactive Home Entertainment' },
  'TPR': { sector: 'Consumer Discretionary', industry: 'Apparel, Accessories & Luxury Goods' },
  'TRGP': { sector: 'Energy', industry: 'Oil & Gas Storage & Transportation' },
  'TGT': { sector: 'Consumer Staples', industry: 'Consumer Staples Merchandise Retail' },
  'TEL': { sector: 'Information Technology', industry: 'Electronic Manufacturing Services' },
  'TDY': { sector: 'Information Technology', industry: 'Electronic Equipment & Instruments' },
  'TER': { sector: 'Information Technology', industry: 'Semiconductor Materials & Equipment' },
  'TSLA': { sector: 'Consumer Discretionary', industry: 'Automobile Manufacturers' },
  'TXN': { sector: 'Information Technology', industry: 'Semiconductors' },
  'TPL': { sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  'TXT': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'TMO': { sector: 'Health Care', industry: 'Life Sciences Tools & Services' },
  'TJX': { sector: 'Consumer Discretionary', industry: 'Apparel Retail' },
  'TKO': { sector: 'Communication Services', industry: 'Movies & Entertainment' },
  'TSCO': { sector: 'Consumer Discretionary', industry: 'Other Specialty Retail' },
  'TT': { sector: 'Industrials', industry: 'Building Products' },
  'TDG': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'TRV': { sector: 'Financials', industry: 'Property & Casualty Insurance' },
  'TRMB': { sector: 'Information Technology', industry: 'Application Software' },
  'TFC': { sector: 'Financials', industry: 'Diversified Banks' },
  'TYL': { sector: 'Information Technology', industry: 'Application Software' },
  'TSN': { sector: 'Consumer Staples', industry: 'Packaged Foods & Meats' },
  'USB': { sector: 'Financials', industry: 'Diversified Banks' },
  'UBER': { sector: 'Industrials', industry: 'Passenger Ground Transportation' },
  'UDR': { sector: 'Real Estate', industry: 'Multi-Family Residential REITs' },
  'ULTA': { sector: 'Consumer Discretionary', industry: 'Other Specialty Retail' },
  'UNP': { sector: 'Industrials', industry: 'Rail Transportation' },
  'UAL': { sector: 'Industrials', industry: 'Passenger Airlines' },
  'UPS': { sector: 'Industrials', industry: 'Air Freight & Logistics' },
  'URI': { sector: 'Industrials', industry: 'Trading Companies & Distributors' },
  'UNH': { sector: 'Health Care', industry: 'Managed Health Care' },
  'UHS': { sector: 'Health Care', industry: 'Health Care Facilities' },
  'VLO': { sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  'VEEV': { sector: 'Health Care', industry: 'Health Care Technology' },
  'VTR': { sector: 'Real Estate', industry: 'Health Care REITs' },
  'VLTO': { sector: 'Industrials', industry: 'Environmental & Facilities Services' },
  'VRSN': { sector: 'Information Technology', industry: 'Internet Services & Infrastructure' },
  'VRSK': { sector: 'Industrials', industry: 'Research & Consulting Services' },
  'VZ': { sector: 'Communication Services', industry: 'Integrated Telecommunication Services' },
  'VRTX': { sector: 'Health Care', industry: 'Biotechnology' },
  'VRT': { sector: 'Industrials', industry: 'Electrical Components & Equipment' },
  'VTRS': { sector: 'Health Care', industry: 'Pharmaceuticals' },
  'VICI': { sector: 'Real Estate', industry: 'Hotel & Resort REITs' },
  'V': { sector: 'Financials', industry: 'Transaction & Payment Processing Services' },
  'VST': { sector: 'Utilities', industry: 'Electric Utilities' },
  'VMRK': { sector: 'Real Estate', industry: 'Multi-Family Residential REITs' },
  'VMC': { sector: 'Materials', industry: 'Construction Materials' },
  'WRB': { sector: 'Financials', industry: 'Property & Casualty Insurance' },
  'GWW': { sector: 'Industrials', industry: 'Industrial Machinery & Supplies & Components' },
  'WAB': { sector: 'Industrials', industry: 'Construction Machinery & Heavy Transportation Equipment' },
  'WMT': { sector: 'Consumer Staples', industry: 'Consumer Staples Merchandise Retail' },
  'DIS': { sector: 'Communication Services', industry: 'Movies & Entertainment' },
  'WBD': { sector: 'Communication Services', industry: 'Broadcasting' },
  'WM': { sector: 'Industrials', industry: 'Environmental & Facilities Services' },
  'WAT': { sector: 'Health Care', industry: 'Life Sciences Tools & Services' },
  'WEC': { sector: 'Utilities', industry: 'Electric Utilities' },
  'WFC': { sector: 'Financials', industry: 'Diversified Banks' },
  'WELL': { sector: 'Real Estate', industry: 'Health Care REITs' },
  'WST': { sector: 'Health Care', industry: 'Health Care Supplies' },
  'WDC': { sector: 'Information Technology', industry: 'Technology Hardware, Storage & Peripherals' },
  'WY': { sector: 'Real Estate', industry: 'Timber REITs' },
  'WSM': { sector: 'Consumer Discretionary', industry: 'Homefurnishing Retail' },
  'WMB': { sector: 'Energy', industry: 'Oil & Gas Storage & Transportation' },
  'WTW': { sector: 'Financials', industry: 'Insurance Brokers' },
  'WDAY': { sector: 'Information Technology', industry: 'Application Software' },
  'WYNN': { sector: 'Consumer Discretionary', industry: 'Casinos & Gaming' },
  'XEL': { sector: 'Utilities', industry: 'Multi-Utilities' },
  'XYL': { sector: 'Industrials', industry: 'Industrial Machinery & Supplies & Components' },
  'YUM': { sector: 'Consumer Discretionary', industry: 'Restaurants' },
  'ZBRA': { sector: 'Information Technology', industry: 'Electronic Equipment & Instruments' },
  'ZBH': { sector: 'Health Care', industry: 'Health Care Equipment' },
  'ZTS': { sector: 'Health Care', industry: 'Pharmaceuticals' },
};

export const SP500_TICKERS = new Set(Object.keys(SP500_BY_TICKER));
